### ISSUE TITLE
Subrun value is always 0 on REve display

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#114]
See for example
<img width="1835" alt="evt20" src="https://github.com/Mu2e/REve/assets/4226815/c357f363-3d08-429b-9fb8-15fb720f4fd6">

**Comment by sophiemiddleton** [comment]
Yes, that is never filled, but I can add it, should be easy mostly these numbers were a test of being able to pass to the GUI. GUI development is my next job
