### ISSUE TITLE
MC trajectory appears truncated

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#115]
The MC trajectory of particles in the CRV appear truncated: compare the REve display here:
<img width="1835" alt="evt1" src="https://github.com/Mu2e/REve/assets/4226815/838ea825-29a7-44c3-a033-11c441f17360">
with the CRV-group display of the same event here:
![Screenshot 2023-08-30 at 3 15 33 PM](https://github.com/Mu2e/REve/assets/4226815/f9029083-b527-428f-a005-fd0599912077)
In the REve display the electron track in the CRV is a tiny stub, while it shows as a more substantial trajectory in the  CRV group display.

**Comment by sophiemiddleton** [comment]
This is probably due to a distance cut I made to avoid large zooms

**Comment by sophiemiddleton** [comment]
I think this is fixed, please check
