### ISSUE TITLE
Allow toggling visibilty of objects from the display window

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#124]
It would be very useful to be able to hide/show individual data elements by selecting them on the display window, for instance, when there are multiple track fits in the event.

**Comment by sophiemiddleton** [comment]
I think we need to make an REveCompound object for each detector then we can remove all at once

**Comment by kutschke** [comment]
I think this is a great idea.  It's important to get the granularity right.   Can I get the best of both worlds: remove, say the calorimeter as a unit but also remove only elements of the calorimeter when I want that?
