### ISSUE TITLE
Add a legend to the display

### ISSUE THREAD

**Issue by lborrel** [Mu2e/REve#125]
For example, what is the difference between the grey and the red crystals, which track color correspond to which particle.
Maybe make a button to toggle the legend on and off

**Comment by sophiemiddleton** [comment]
Thanks Leo, we had this in our TEve version. We are waiting on some new Rendering from ROOT to get it up and running. You can find particle type in the meantime by hovering over any MCTraj and it should say the name and sign of the true particle

**Comment by sophiemiddleton** [comment]
@sam-grant I spoke with the REve developers, this is not currently in the latest ROOT, they have something in their branch but are not ready to release. So let's pause this one

**Comment by sam-grant** [comment]
OK. Let me know when they've released their update.
