### ISSUE TITLE
Improving geometry displays for PS,TS and remote handling room

### ISSUE THREAD

**Issue by sophiemiddleton** [Mu2e/REve#128]
A suggestion to use the REve display as an alternative to geometry browsing. We currently only have a crude outline of the PS, TS and production target. To do MC beam studies we might want to improve the view and Sridhar is to start thinking about what we might want here

**Comment by sophiemiddleton** [comment]
@sridhar130 is this something you'd still like to pursue?

**Comment by sridhar130** [comment]
Hi @sophiemiddleton, If someone else is attempting then it's alright. But, next month I can try to pursue it.

**Comment by sophiemiddleton** [comment]
No worries, I think there's a more general action item which is more pressing, but if you still think this is something you want to add then let me know. If not then we can close the issue
