### ISSUE TITLE
segv when 'quit root' is selected

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#136]
The REve framework job crashes with 'segv' when the browser 'quit root' button is pressed.  The stack trace shows this is happening inside of root.  I suspect the TApplication needs to be told that the loop is ending, perhaps roottalk might have an answer.

Thread 2 "mu2e" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff34d35700 (LWP 17706)]
0x00000000038384b0 in ?? ()
(gdb) where 10
#0  0x00000000038384b0 in ?? ()
#1  0x00007fffecbd9f48 in TUnixSystem::DispatchOneEvent (this=0x7e8b20, pendingOnly=<optimized out>)
    at /scratch/workspace/canvas-products-all/v3_16_01a-/SLF7/e28-prof/build/root/v6_28_10a/source/root-6.28.10/core/unix/src/TUnixSystem.cxx:1051
#2  0x00007fffecaf3dc9 in TSystem::InnerLoop (this=0x7e8b20) at /scratch/workspace/canvas-products-all/v3_16_01a-/SLF7/e28-prof/build/root/v6_28_10a/source/root-6.28.10/core/base/src/TSystem.cxx:406
#3  TSystem::Run (this=0x7e8b20) at /scratch/workspace/canvas-products-all/v3_16_01a-/SLF7/e28-prof/build/root/v6_28_10a/source/root-6.28.10/core/base/src/TSystem.cxx:356
#4  0x00007fffeca8a7a3 in TApplication::Run (this=0x44bf780, retrn=<optimized out>) at /scratch/workspace/canvas-products-all/v3_16_01a-/SLF7/e28-prof/build/root/v6_28_10a/source/root-6.28.10/core/base/src/TApplication.cxx:1677
#5  0x00007ffff72ca14f in std::execute_native_thread_routine (__p=0xdd8970) at /scratch/workspace/art-build-base/v13_02_00-e28/SLF7/build/gcc/v13_1_0/src/gcc-13.1.0/libstdc++-v3/src/c++11/thread.cc:104
#6  0x00007ffff4abeea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff6cfdb0d in clone () from /lib64/libc.so.6

**Comment by sophiemiddleton** [comment]
Dave I dont see this error when I run that button, maybe we should discuss

**Comment by brownd1978** [comment]
I still see this.
