### ISSUE TITLE
CRV bars aren't transparent

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#137]
With root 6.28 transparency is working (great).  However the hit CRV bars are shown as solid, not transparent.  They should have the same transparency as the geometry.

<img width="2316" alt="reve_crv" src="https://github.com/Mu2e/REve/assets/4226815/b94d1319-5dd6-440b-a8e5-ca85400f5a3e">

**Comment by kutschke** [comment]
A few wild guesses.  I believe that the G4 model has the wrapping of the bars.  There are also spacers between bars.  I think, but am not sure, there are are per module mother volumes.  All need to have the right transparency settings.   Have you looked into that?

It's also possible that we need to do somethning different in the Offline/G4 interface code that creates the volumes.

**Comment by kutschke** [comment]
... I should have said absorbers between bars, not spacers.  They are Al I believe.

**Comment by sophiemiddleton** [comment]
I dont think so, the coloring is purely on REve as far as I recall so its an REve thing

**Comment by sophiemiddleton** [comment]
I need to check with the developers on this, it seems something isnt propagating correctly and its not in our code (there was a previous issue which was solved elsewhere but not here)

**Comment by sophiemiddleton** [comment]
Oh, actually I think it might just be that the lines are really thick 
![Screen Shot 2024-05-06 at 7 43 29 PM](https://github.com/Mu2e/REve/assets/4170148/7446a521-31bc-4f7f-8a37-9001d8ecc239)

**Comment by sophiemiddleton** [comment]
(let me t
