### ISSUE TITLE
calo clusters not shown in extracted position

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#138]
Nothing is drawn on event which has a calo cluster in extracted position, with all the flags and collection ID set correctly:
<img width="2316" alt="REve_nocalo" src="https://github.com/Mu2e/REve/assets/4226815/220ed794-1367-43a4-ba22-3deb8500e602">

**Comment by sophiemiddleton** [comment]
seems this issue has spread....I dont know where they have gone, I will debug

**Comment by sophiemiddleton** [comment]
Ah @brownd1978 it seems that its something in the new .fcl you pushed. Using an older version I can now see them....I wonder what is interferring with the clusters, and why its just them.... I will try to isolate the issue
