### ISSUE TITLE
Fix a "go to event" GUI based selector

### ISSUE THREAD

**Issue by sophiemiddleton** [Mu2e/REve#147]
Almost done

**Comment by sophiemiddleton** [comment]
See comment on the general enhancements issue:https://github.com/Mu2e/REve/issues/132

**Comment by sophiemiddleton** [comment]
There is an issue here (or with any feedback to the module). The GUI lives in a separate thread from the application. I can pass information from the module to the GUI, I can input information on the GUI and print it from the GUI C++ class (i.e. the input works) but I cannot pass that input value back to the module.

This seems to be a C++ issue associated with c++ threads, I need to figure out a general fix and we would then have a lot of new features on REveMu2e

**Comment by kutschke** [comment]
> ... but I cannot pass that input value back to the module.

There must be a way to do bi-directional communication.  Brute force is to sue mutex controlled variables that are available in both threads.  I am sure that there are better ways.  For help with this sort of question, start by making an issue on the art issue tracker.  Even though this is not strictly an art issue is about operating within art and the art team does have the expertise to help with this.

**Comment by sophiemiddleton** [comment]
I opened an issue: https://github.com/art-framework-suite/art/issues/147
