### ISSUE TITLE
MCTrajector for a CE doesn't originate in the target

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/REve#159]
This might be a problem with the target position or a truncation of the MCTrajectory object itself.
Reproduce with:
 mu2e -c REve/examples/nominal_example.fcl /pnfs/mu2e/tape/phy-sim/mcs/mu2e/CeEndpointOnSpillTriggered/MDC2020ae_best_v1_3/art/74/86/mcs.mu2e.CeEndpointOnSpillTriggered.MDC2020ae_best_v1_3.001210_00000000.art
<img width="971" alt="target_offset?" src="https://github.com/Mu2e/REve/assets/4226815/acbcecd0-5fef-4584-bba6-2be5a0402a8e">

**Comment by sophiemiddleton** [comment]
I've not seen this before either.....

**Comment by sophiemiddleton** [comment]
related to the general https://github.com/Mu2e/REve/issues/171
