### ISSUE TITLE
Fix code to give better error messageing and use art functionality to not have to state all input parameters in fcl

### ISSUE THREAD

**Issue by sophiemiddleton** [Mu2e/REve#78]
It has been noted that for some time there is an issue with user's having to specifically list all input tags they want to display in the .fcl file. This is hard to maintain and leads to errors if the wrong tag is used, and the messages are not very useful to help diagnose that this is the issue. I propose:

* better error messages
* edit code to more easily adapt to any input tag for a given parameter

**Comment by sophiemiddleton** [comment]
- utilizing the getMany function [x]
- patching up the data interface to use the output of this [TODO]

**Comment by sophiemiddleton** [comment]
The code now "works" for the first event, but for some reason doesnt store anything after that ... investigating

**Comment by kutschke** [comment]
When you say "store anything" do you mean that you have a RootOutput module in your path but that does not create an output file?

Are you using the feature or art that lets you rewind the input file and reply events?

**Comment by sophiemiddleton** [comment]
I just mean use getMany to allow for any given choices by the user. The issues is that its filling the list of say clusters but that its not drawing them at the draw stage, after  the first event. It's probably unrelated to the change in input, and perhaps just part of the code which has not been tested yet
